### ISSUE TITLE
Error on saving a few object (different types) with the same guid

### ISSUE THREAD

**Issue by ivan-luxoft** [Luxoft/BSSFramework#302]
we have entities that have the same id and sometimes we need to simultaneously add them to db.
Then we are getting error:
```
System.InvalidOperationException: Sequence contains more than one matching element
at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at Framework.DomainDriven.DALChangesExtensions.ToFinalState(IReadOnlyDictionary`2 states) in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.Core/Session/DALChanges/DALChangesExtensions.cs:line 105
at Framework.DomainDriven.DALChangesExtensions.<>c.<Composite>b__4_4(IGrouping`2 changeGroup) in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.Core/Session/DALChanges/DALChangesExtensions.cs:line 59
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at Framework.DomainDriven.DALChangesExtensions.Composite(IEnumerable`1 source) in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.Core/Session/DALChanges/DALChangesExtensions.cs:line 53
at Framework.DomainDriven.NHibernate.WriteNHibSession.FlushAsync(Boolean withCompleteTransaction, CancellationToken cancellationToken) in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.NHibernate/NhibSessions/WriteNHibSession.cs:line 262
at Framework.DomainDriven.NHibernate.WriteNHibSession.CloseAsync(CancellationToken cancellationToken) in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.NHibernate/NhibSessions/WriteNHibSession.cs:line 159
at Framework.DomainDriven.NHibernate.NHibSessionBase.DisposeAsync() in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.NHibernate/NhibSessions/NHibSessionBase.cs:line 70
at Framework.DomainDriven.NHibernate.NHibSession.DisposeAsync() in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.NHibernate/NhibSessions/NHibSession.cs:line 106
at Framework.DomainDriven.IDBSession.System.IDisposable.Dispose() in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.Core/Session/IDBSession.cs:line 55
at Framework.DomainDriven.DBSessionEvaluator.EvaluateAsync[TResult](DBSessionMode sessionMode, Func`3 getResult) in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.Core/Session/DBSession/DBSessionEvaluator.cs:line 38
at Framework.DomainDriven.DBSessionEvaluator.EvaluateAsync[TResult](DBSessionMode sessionMode, Func`3 getResult) in /home/runner/work/BSSFramework/BSSFramework/src/_DomainDriven/Framework.DomainDriven.Core/Session/DBSession/DBSessionEvaluator.cs:line 38
```

test to reproduce that:
https://github.com/Luxoft/BSSFramework/commit/46435c8aed2efdab87f47965aa243efbdebccb5c

as workaround we add db flush between inserting objects

**Comment by ivan-luxoft** [comment]
Fixed in #303  [20.0.24](https://github.com/Luxoft/BSSFramework/releases/tag/20.0.24)
